### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Psaurin** [quackest/dancetools#2]
I press the button, nothing happens.. I have it installed, not sure what to do.

**Comment by quackest** [comment]
Are you loaded into a match? Like not in main menu?
I maybe should've specified that you can only open it while you are in game. Might need to adjust it and potentially get it working while in main menu

**Comment by quackest** [comment]
Hey, I just pushed an update that allows you to change the keybind to the console key in the config. Should be located in your `BepInEx/config/dancemoon.lethalcompany.dancetools.cfg`

**Comment by Psaurin** [comment]
Alright, thank you!! I'll reply again if I have issues

**Comment by Psaurin** [comment]
I'm not sure I'm downloading it properly, more instructions/pictures/a video would be greatly appreciated. I'll keep trying, though.

**Comment by Psaurin** [comment]
Okay, so I don't see a DanceTools.dll, but I see a DanceTools.cs

**Comment by Psaurin** [comment]
Do I put DanceTools.dll into /DanceTools/?

**Comment by Psaurin** [comment]
I was in game, and in the building on experimentation whilst I attempted to open it. I have /DanceTools/ in a folder along with the required console item inside. The dll is outside of the folder. All in /Plugins/ by the way.

**Comment by quackest** [comment]
> Do I put DanceTools.dll into /DanceTools/?

No, the .dll should be in the Plugins folder

> I was in game, and in the building on experimentation whilst I attempted to open it. I have /DanceTools/ in a folder along with the required console item inside. The dll is outside of the folder. All in /Plugins/ by the way.

Is it just randomly not working? Or does it not work at all? Could you maybe try rebinding the key?

This is how the plugin in the plugins folder should look like: 
![image](https://github.com/quackest/dancetools/assets/48807848/eee9fb14-d14b-4925-a1b5-21234ede3a20)

**Comment by Psaurin** [comment]
![image](https://github.com/quackest/dancetools/assets/120991366/0d317e99-e7fc-4119-a80a-f758f547a077)
No option to rebind shows up in bind menu, is there any specific way I have to launch the game/did I install it correctly?

**Comment by quackest** [comment]
Oh, do you have bepinex installed? You need it to use my plugin. Here is a guide on how to install it manually (not sure if you're using any mod manager)
https://docs.bepinex.dev/articles/user_guide/installation/index.html

**Comment by Psaurin** [comment]
I am using BepinEX, and I'd prefer we speak over another platform if you're okay with that, it would make communication faster.

**Comment by quackest** [comment]
Sure, my discord username is `dancemoon`

**Comment by Psaurin** [comment]
it says you have to add me.. Psaurin

**Comment by quackest** [comment]
Fixed issue thru discord. Bepinex was not properly installed
