### ISSUE TITLE
its not working

### ISSUE THREAD

**Issue by lethalcompanymodder** [quackest/dancetools#3]
I downloaded the mod from thunderstore mod manager, but when i press ~ nothing happens, i am in a game sitting in my ship but it isnt working. Could you change the keybind to F5 or something because i cant get this to work and it seems like the only good menu i can find
I think i have may found the problem, my keyboard wont let me use "~" ingame it only will let me use ` and i dont know how to change it

**Comment by quackest** [comment]
Hey, I just pushed an update that allows you to change the keybind to the console key in the config. Should be located in your `BepInEx/config/dancemoon.lethalcompany.dancetools.cfg`

**Comment by lethalcompanymodder** [comment]
> BepInEx/config/dancemoon.lethalcompany.dancetools.cfg
how do i get there

**Comment by quackest** [comment]
> > BepInEx/config/dancemoon.lethalcompany.dancetools.cfg
> > how do i get there

One way to get there is to go to the steam library, right click lethal company, under the manage tab, click browse local files. After that you should be inside your install directory. Open Bepinex folder and inside there should be config folder

**Comment by lethalcompanymodder** [comment]
> > > BepInEx/config/dancemoon.lethalcompany.dancetools.cfg
> > > how do i get there
> 
> One way to get there is to go to the steam library, right click lethal company, under the manage tab, click browse local files. After that you should be inside your install directory. Open Bepinex folder and inside there should be config folder

i dont have that folder for some reason

**Comment by quackest** [comment]
> > > > BepInEx/config/dancemoon.lethalcompany.dancetools.cfg
> > > > how do i get there
> > 
> > 
> > One way to get there is to go to the steam library, right click lethal company, under the manage tab, click browse local files. After that you should be inside your install directory. Open Bepinex folder and inside there should be config folder
> 
> i dont have that folder for some reason

Do you mean you dont have the config file inside the config folder? To generate it, you need to launch the game once and it should be there

Or do you mean you don't have the bepinex folder?

Could you possibly send me a screenshot of your games install directory and bepinex folder?

**Comment by lethalcompanymodder** [comment]
yea i dont have the bepinex folder
only two folders i have are  "Lethal Compnany_Data"
and MonoBleedingEdge

**Comment by quackest** [comment]
> yea i dont have the bepinex folder only two folders i have are "Lethal Compnany_Data" and MonoBleedingEdge

oh interesting. are you using the mod manager? that may cause it. I haven't tried installing it using the mod manager and no idea how it works

**Comment by smashbombs** [comment]
[Error  : Unity Log] Unable to open archive file: C:/Users/smash/AppData/Roaming/Thunderstore Mod Manager/DataFolder/LethalCompany/profiles/Default/BepInEx/plugins/dancemoon-DanceTools/DanceTools/dancetoolsconsole
How do ifix this. i am using the thunderstore mod manager.

**Comment by quackest** [comment]
This should be fixed with version 1.1.2 of the plugin. It now does an extra check if the assetbundle is in the DanceTools folder or the same folder as the plugin
