### ISSUE TITLE
I dont think this plays nice when using a modmanager like thunderstore or R2modman

### ISSUE THREAD

**Issue by gerpyy** [quackest/dancetools#5]
I didnt have much issue when it was all chat based commands but now that it uses a config and console I can no longer use the mod. The config doesn't show up in the mod manager and when I push ~ nothing happens unfortunately.

**Comment by eZephyr1** [comment]
I have looked under my bepinex config folder to try and manually find the config file but there just isn't one even after launching the game several times.

**Comment by quackest** [comment]
Interesting. I'm not sure how the mod manager works for thunderstore or r2modman, ill have a look at it

**Comment by Aerobiker** [comment]
Hi, i also use R2modman, and the only modification i had to do is to put the file "dancetoolconsole" into a file i had to make called "DanceTools". Then everything loaded properly and the config file got created. 

An idea to fix this may be to just use a double try, where you try to load the "danceconsole" then try to load "../danceconsole" or something. 

How its installed :
![image](https://github.com/quackest/dancetools/assets/116542129/6e19b2c6-067c-41a5-9787-a0f6f2ae97e0)

What i did :
![image](https://github.com/quackest/dancetools/assets/116542129/512fa0bf-e034-419f-8bb5-3b2180ba816a)
![image](https://github.com/quackest/dancetools/assets/116542129/38fdd54c-8cc5-4ae0-80ad-cbd34d39c1bd)

**Comment by gerpyy** [comment]
I did what Aerobiker said and can confirm it worked just fine!

**Comment by mastchiefqueef** [comment]
Shows this when using thunderstorm manager 
![image_2023-12-22_164100570](https://github.com/quackest/dancetools/assets/101538776/df7188ac-184b-41b5-8d9a-1e0177ec1c1a)
 I even made the "DanceTools" folder

**Comment by quackest** [comment]
> Hi, i also use R2modman, and the only modification i had to do is to put the file "dancetoolconsole" into a file i had to make called "DanceTools". Then everything loaded properly and the config file got created.
> 
> An idea to fix this may be to just use a double try, where you try to load the "danceconsole" then try to load "../danceconsole" or something.

I'll give it a shot, I'll check the plugin folder for the assetbundle AND the ./DanceTools/ when loading the assets. This could fix the issue, ty!

**Comment by dhkatz** [comment]
> I did what Aerobiker said and can confirm it worked just fine!

Can confirm this also worked. Although the console still printing what mastchiefqueef posted

**Comment by sword11247** [comment]
install with thunderstore then manual install and copy paste Dancetools folder the contains the console and delete the console from the file thats being used as the mod then paste the dancetools folder

**Comment by sword11247** [comment]
it should look like this
![image](https://github.com/quackest/dancetools/assets/122589621/83db0ad3-fb0d-47f4-8926-2c25da264675)

**Comment by Supertheobrg** [comment]
Do the #8 said and don't take care of the error ! 

Config files : 
\BepInEx\config
and for the keybind use this website 
https://docs.unity3d.com/ScriptReference/KeyCode.html

**Comment by quackest** [comment]
This should be fixed with version 1.1.2 of the plugin. It now does an extra check if the assetbundle is in the DanceTools folder or the same folder as the plugin
