### ISSUE TITLE
Value is 1

### ISSUE THREAD

**Issue by Ryanisunique107** [quackest/dancetools#6]
spawned a laser and a gold bar both valued at 1 and both sold for one only got 2 for quota please fix thankyou in advance

**Comment by quackest** [comment]
Are you sure you are using the command correctly? I just tried it and it works fine for me, even selling the item gives me the value i specified.
`item itemID amountOfItems valueOfItems`
`item 36 1 1000` <- 1 gold bar valued at 1000

**Comment by Ryanisunique107** [comment]
sorry my bad thanks
