### ISSUE TITLE
not a issue but a fix to the console issue

### ISSUE THREAD

**Issue by sword11247** [quackest/dancetools#8]
install using thunderstore then manual download the lastest file delete the console in thunderstore bepinex plugins folder then copy paste dancetools from the manual download one paste in the dancetool folder in the pluggins and your folder should look something like this
![image](https://github.com/quackest/dancetools/assets/122589621/881c5fef-4844-4e9a-b007-5837b07e12f2)

**Comment by sword11247** [comment]
if you see dancetoolsconsole outside the folder delete it and add the dancetools folder

**Comment by Supertheobrg** [comment]
[Warning: Unity Log] The referenced script (ConsoleScript) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'DanceToolsConsole') is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object '<null>') is missing!
[Warning: Unity Log] The referenced script (ConsoleScript) on this Behaviour is missing!
[Warning: Unity Log] The referenced script on this Behaviour (Game Object 'DanceToolsConsole') is missing!

**Comment by quackest** [comment]
This should be fixed with version 1.1.2 of the plugin. It now does an extra check if the assetbundle is in the DanceTools folder or the same folder as the plugin
